const LOREM_IPSUM: &'static str = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae lorem a purus semper imperdiet sit amet eget arcu. Nullam quis risus sapien. Donec sagittis ex quis urna suscipit, sed pharetra est ornare. Pellentesque mollis libero eu orci convallis fringilla. Sed non varius elit, in accumsan risus. Aliquam eros eros, vestibulum a ullamcorper viverra, sagittis nec lacus. Aliquam metus mauris, ornare tempor purus id, gravida euismod mi. Nam et blandit augue, vitae luctus dui. Fusce blandit, leo sodales aliquet dictum, nibh est condimentum felis, eu interdum diam turpis eget ante.

Aliquam iaculis congue magna. Aenean ac purus nisi. Nam sed nulla a elit ultricies eleifend eu vel leo. Morbi dapibus sem nibh, malesuada vehicula nisi rhoncus eget. Aenean aliquam vestibulum lacus eu varius. Suspendisse eleifend congue ex a placerat. Pellentesque erat metus, condimentum eget urna sed, gravida lacinia metus. Morbi elementum nisl et massa molestie, non pretium justo accumsan. Suspendisse sollicitudin est at faucibus eleifend. Mauris sit amet mauris id est tempor tempor vitae sit amet mauris. Cras urna risus, dictum non viverra a, porta vel tellus. Aenean tincidunt elit in lacus efficitur fermentum.

Mauris sodales tempus libero at porta. Donec scelerisque tincidunt dui, et ornare sapien hendrerit vel. Duis varius vitae lacus consectetur luctus. Etiam non ipsum metus. Nunc quam felis, volutpat sed auctor quis, placerat ornare purus. Ut interdum sapien vel nunc auctor, quis luctus tellus porta. Vivamus id lacinia ex, vitae faucibus libero. Suspendisse potenti. Phasellus auctor quam eget purus interdum aliquet a ut eros. Etiam sit amet nulla ut lacus feugiat finibus. Proin pharetra tortor non ex placerat tristique.

Curabitur pulvinar ac lacus vitae viverra. Nullam pretium enim lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur volutpat odio vitae sem ullamcorper, sed aliquet nulla convallis. Maecenas porta accumsan velit. Ut scelerisque nunc eu massa lobortis, congue rutrum nisl pellentesque. Quisque ligula tellus, porta non metus ut, fermentum fringilla quam. Mauris sagittis neque lacinia justo ullamcorper rhoncus. Aenean venenatis consectetur purus, laoreet hendrerit arcu fermentum blandit. Nunc tincidunt justo eros, vel tristique metus ullamcorper at. Nullam a augue molestie, lobortis urna in, varius purus. Cras eleifend condimentum nibh, eget posuere neque pharetra vel. Sed placerat, enim sed hendrerit rhoncus, lectus ante dictum orci, vitae vestibulum tortor justo sit amet libero. Duis at massa velit. Vestibulum blandit cursus ultrices.

Vivamus a leo in urna euismod feugiat fringilla id nisl. Vestibulum orci tellus, malesuada a sem non, placerat pretium leo. Quisque rhoncus dui ac facilisis pulvinar. Etiam sagittis, dolor in commodo posuere, leo ligula consequat nulla, a lobortis ante augue a magna. Vivamus ultricies lorem vitae metus hendrerit, fringilla suscipit leo gravida. Cras varius enim mi, sed molestie lacus tristique non. Donec risus diam, scelerisque id fringilla ut, scelerisque ac lorem. Nulla et bibendum quam. Cras eu dignissim justo. Morbi interdum mollis ligula, id laoreet felis vehicula vel. Nam efficitur gravida mi vitae feugiat. Morbi iaculis sapien tortor, sed mollis tortor finibus a. Morbi efficitur risus a ipsum ultricies condimentum.

Proin tincidunt condimentum ipsum, sit amet tincidunt mauris rhoncus non. Proin id augue ex. Aliquam eu mauris erat. Phasellus pulvinar quam ac mauris euismod facilisis. Aliquam erat volutpat. Praesent tempor vel mauris sed scelerisque. Nulla tincidunt, nisi at consectetur vehicula, dui metus finibus ex, eu consequat augue arcu vel nunc.

Nulla at ante porttitor, efficitur nisi vel, scelerisque neque. Etiam lacinia, dui et sagittis maximus, lorem ligula vestibulum nulla, vel dignissim ipsum urna non nulla. Praesent malesuada rutrum elit sit amet porttitor. Aliquam finibus scelerisque turpis et tincidunt. Morbi consectetur blandit laoreet. In metus lectus, lobortis ut risus ut, posuere dapibus nisl. Ut vitae ex quis nisl maximus dictum in vel elit. Suspendisse faucibus tortor nec lacus volutpat vestibulum. Phasellus nisi magna, pretium quis iaculis vitae, ornare sit amet massa. Fusce posuere lorem mollis est fringilla lobortis in et dui.

Morbi at dictum magna. Vestibulum aliquet vulputate tortor, in fringilla ligula lacinia in. Ut et vehicula augue. Integer vitae risus venenatis, convallis ipsum a, placerat arcu. Suspendisse dignissim ex eleifend, feugiat elit a, ullamcorper tortor. Integer pellentesque dolor eget pharetra finibus. Cras porttitor, odio eu elementum gravida, mauris lorem ornare dolor, quis tempor mi sem ut ipsum. Fusce ac ornare tellus. Nulla velit quam, ultrices pulvinar orci ac, lobortis interdum tortor. Morbi ac congue nunc. In id cursus orci. Mauris ac lobortis dolor. Cras vitae massa eget eros ornare pulvinar. Cras elementum pellentesque metus. Vestibulum non tortor bibendum, euismod arcu vitae, vehicula dui. Curabitur porttitor leo aliquam feugiat dignissim.

Donec vitae efficitur enim. Duis sit amet rutrum libero. Curabitur tortor risus, eleifend id lectus eu, malesuada rutrum nunc. Praesent at libero porta, pulvinar enim et, venenatis nisi. Ut bibendum luctus augue quis vestibulum. Pellentesque id lectus augue. Pellentesque porta mi nibh, ac laoreet enim tempor sed. Quisque eu pulvinar enim. Suspendisse posuere, leo a tempor maximus, nisi tortor dapibus lorem, id iaculis erat tortor et risus. Nullam porta semper felis, lacinia fermentum leo convallis ut. Integer arcu diam, rhoncus ut dui a, volutpat fringilla nisi. Phasellus id sem ac diam pulvinar ullamcorper. Vivamus luctus dapibus tortor vitae lacinia.

Vivamus at pretium arcu. Mauris varius faucibus diam ut egestas. Nam vel nulla sit amet augue rhoncus porttitor quis nec nibh. Suspendisse in vulputate ante. Morbi elementum massa ut magna ullamcorper, sodales ultricies sem interdum. Donec eleifend ex dolor, id finibus magna vulputate in. Aenean malesuada, nisl non posuere fermentum, arcu mauris malesuada leo, ut porttitor erat neque at eros. Integer interdum nisl sit amet sapien commodo, nec commodo leo sagittis. Donec volutpat consectetur mauris, et semper libero porttitor vitae. Cras cursus leo ante, ac ornare nisl volutpat ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi imperdiet, ipsum eget placerat rhoncus, nisi augue sollicitudin lorem, sed interdum tellus magna maximus ligula.

Pellentesque ante erat, facilisis ut mollis ac, ullamcorper eget metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam imperdiet semper pulvinar. Vestibulum volutpat mattis molestie. Praesent eget enim dui. Nulla pulvinar, augue non iaculis fermentum, erat tortor vehicula nunc, sed interdum nulla nunc vitae diam. Nam vulputate scelerisque nulla et gravida. Curabitur a lacinia purus. Donec vitae lectus at ex dignissim euismod. Morbi nec dolor pretium, ornare nibh quis, condimentum urna. Nam accumsan ligula a orci posuere ornare. Pellentesque dictum feugiat quam nec vulputate. Nunc hendrerit placerat tempor. Vivamus eu porta augue. Vivamus faucibus et ligula et feugiat.

Phasellus eu malesuada magna. Cras finibus sed lorem id finibus. Sed ut nisl ante. Vestibulum pulvinar semper augue, et eleifend eros. Vivamus porttitor ex ac felis convallis rutrum. Aliquam nec nibh metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas venenatis imperdiet ligula quis tempor. Morbi efficitur lobortis mattis. Pellentesque at lacinia metus. Quisque maximus sapien sit amet accumsan rutrum. Sed et maximus nibh. Fusce turpis nisi, suscipit id maximus in, hendrerit vitae sapien. Nunc nec sem placerat, mollis est sed, sagittis augue. Nunc sit amet ex congue libero malesuada placerat.

Etiam id pellentesque nibh. Praesent at porta tellus. In hac habitasse platea dictumst. Aliquam dolor leo, facilisis quis nisi at, faucibus tempus orci. Etiam ullamcorper libero eget tortor sagittis, nec rhoncus orci posuere. Mauris sed orci fringilla, tincidunt lorem ac, laoreet elit. Phasellus porttitor, justo at condimentum facilisis, leo nisl pharetra eros, eget sagittis elit sapien vitae justo. Sed nec urna non ante gravida mollis. Etiam efficitur suscipit felis at imperdiet. Sed sed felis nec magna semper dignissim. Etiam eget placerat velit, sed convallis ex. Maecenas hendrerit nisl feugiat ante molestie faucibus.

Mauris ultrices aliquet tortor. Pellentesque sit amet consequat augue, non pulvinar odio. Donec vehicula, erat vitae molestie ultrices, enim ipsum posuere eros, vitae tincidunt risus ligula ac dui. In eget eros molestie, tempor eros et, mattis dui. Suspendisse sed purus sit amet diam interdum semper. Nam lobortis sagittis laoreet. Donec mi neque, mattis in posuere nec, tempor at ante. Sed porttitor mattis venenatis. Etiam non lorem venenatis felis consectetur interdum vitae efficitur magna. Donec in tortor felis.

Ut malesuada nunc at leo dictum semper. Proin pretium ipsum eget tempor maximus. Integer in porttitor erat, id tristique nunc. Duis turpis nibh, pellentesque ut nulla vel, posuere dapibus quam. Fusce ac turpis ac ipsum porttitor tincidunt ut vel diam. Quisque gravida nibh ut eleifend congue. Pellentesque rutrum dui sed diam vehicula eleifend. Duis diam lorem, luctus nec venenatis nec, sagittis non ex. Quisque ac feugiat magna. Nunc eleifend mauris at pharetra pellentesque. Phasellus tincidunt turpis sed est scelerisque, vel tristique magna finibus.

Vivamus quis mi metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus laoreet sodales placerat. Nulla facilisi. Curabitur hendrerit ornare malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse ut laoreet mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id urna finibus, aliquam lectus id, tincidunt quam. In sed tristique ante. Morbi pellentesque lobortis odio, id rutrum nisl eleifend sit amet. In a turpis sed mauris consequat cursus. Sed a mattis nibh. Vestibulum vel maximus orci. Nam dictum id magna eu malesuada. Vestibulum tincidunt lacus a enim pretium, eget convallis metus aliquet.

Nunc efficitur vestibulum placerat. Donec orci nunc, blandit in lectus in, pulvinar aliquet tellus. Pellentesque congue maximus nisl aliquam mattis. Nullam tempus ante eu ligula iaculis, a varius diam sollicitudin. Proin a dapibus nisi. Suspendisse eget pharetra diam, a venenatis enim. Donec eget mauris lorem. Donec a orci faucibus, vestibulum velit id, feugiat metus. Vivamus a ipsum sit amet urna dictum tincidunt.

Sed scelerisque dolor ut pharetra gravida. Integer nec viverra lectus. Integer quis velit dictum, eleifend magna a, tincidunt libero. Donec sed ex lorem. Sed sed malesuada dolor. Ut auctor placerat ipsum ut venenatis. Suspendisse a euismod sapien. Pellentesque accumsan tortor et porta tempor. Ut vulputate interdum mi bibendum condimentum. Sed semper pulvinar mattis. Aliquam sit amet mattis nibh, sit amet vehicula lectus.

Nam rutrum molestie odio, at cursus ex fermentum id. Curabitur feugiat urna arcu, sed auctor massa tristique vel. Praesent cursus ullamcorper nisi, non commodo urna. Nulla eget elit fringilla, pulvinar dui eget, vestibulum ipsum. In non sodales turpis, euismod imperdiet eros. Duis tempor felis a bibendum blandit. Nulla ut leo eu ante tempor pellentesque a vel ligula. Cras molestie non libero ac imperdiet. Nunc id fermentum ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus lobortis nisl euismod, cursus nisi in, auctor nunc. Mauris convallis maximus ante, quis scelerisque lacus malesuada quis.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce vehicula nibh sit amet sodales tincidunt. Suspendisse potenti. Phasellus vitae lectus vel lorem congue hendrerit eget eget nisl. Pellentesque sed fermentum lacus, mattis commodo nunc. Phasellus interdum tempus fringilla. Nulla ullamcorper justo est, sed venenatis lorem semper ut. Suspendisse sollicitudin mollis mi quis sodales. Donec id cursus erat. Nunc molestie erat sit amet sapien tincidunt volutpat eu in felis. 
";
